# Generated by Django 5.2.12 on 2026-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
